name       : x2goclient
version    : 4.0.5.1
release    : 1
source     :
    - http://code.x2go.org/releases/source/x2goclient/x2goclient-4.0.5.1.tar.gz : 844e983fbbddfe8a626506e4140b1ad65591e14f794c735412402bee3163ed11
license    : GPL-2.0
component  : network.util
summary    : x2go remote desktop client
description: |
    X2Go is an open source remote desktop software for Linux that uses the NX technology protocol. X2Go gives remote access to the Linux graphical user interface. It can also be used to access PC desktops. It provides secure remote sessions via ssh.
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(QtCore)
    - pkgconfig(xpm)
    - pkgconfig(x11)
    - cups-devel
    - nxcomp-devel
    - nxproxy
    - openldap-devel
setup      : |
    # softlinks needed in build environment
    ln -sf /usr/bin/qmake-qt4 /usr/bin/qmake
    ln -sf /usr/bin/lrelease-qt4 /usr/bin/lrelease
    ln -sf /usr/bin/uic-qt4 /usr/bin/uic
    ln -sf /usr/bin/moc-qt4 /usr/bin/moc
    ln -sf /usr/bin/rcc-qt4 /usr/bin/rcc
    %patch -p1 < $pkgfiles/0001-config_makefile.patch
build      : |
    make all
install    : |
    %make_install
