name       : x2goclient
version    : 4.1.2.1
release    : 8
source     :
    - https://code.x2go.org/releases/source/x2goclient/x2goclient-4.1.2.1.tar.gz : 1c18981f0a39929624de9472b0e6c3fa2ac7842837dd306db318af54c5fff2af
license    : GPL-2.0-or-later
component  : network.util
summary    : x2go remote desktop client
description: |
    X2Go is an open source remote desktop software for Linux that uses the NX technology protocol. X2Go gives remote access to the Linux graphical user interface. It can also be used to access PC desktops. It provides secure remote sessions via ssh.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libssh)
    - pkgconfig(xpm)
    - cups-devel
    - openldap-devel
rundeps    :
    - nx-libs
setup      : |
    sed -i -e 's/-o root -g root//' Makefile
    sed -i -e 's/-qt4//' Makefile
    sed -e 's/-lssh_threads//' -i x2goclient.pro    # Fix build with libssh 0.8
    %patch -p1 < $pkgfiles/x2goclient-qt5.11.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
